import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "User",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <div className="flex flex-col min-h-screen h-full">{children}</div>;
}
