export type Review = {
  id: string;
  title: string;
  img: string;
  genres: string;
  platforms: string;
  releaseDate: string;
  status: string;
  playTime: string;
  gameScore: number;
  plotScore: number;
  artScore: number;
  gameplayScore: number;
  difficulty: string;
  plot: string;
  review: string;
  isFavorite: boolean;
  createdAt?: string;
  updatedAt?: string;
};
