### Registration
POST http://localhost:4000/auth/registration
Content-Type: application/json

{
    "name": "Ihar",
    "email": "wimx@tut.by",
    "password": "12345lL@"
}

### Verify registration Token
GET http://localhost:4000/auth/verify/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwODJmMTg1YS1jZWVkLTQ2NDktODE1My03YjljMDc0YzNhYTciLCJpYXQiOjE3MjgyMTU1MjcsImV4cCI6MTcyODMwMTkyN30.8F89XnCfvhrtA792_cKM5vZJ_LTmGkX9FxkiVq8k2E8

