### Registration
POST http://localhost:4000/auth/registration
Content-Type: application/json

{
    "name": "Ihar",
    "email": "wimx@tut.by",
    "password": "12345lL@"
}

### Verify registration Token
GET http://localhost:4000/auth/verify/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmNzdiNjdmZS0wYjc2LTQyOTEtOTVmYS0yM2QwOWMzNTc1YjEiLCJpYXQiOjE3MjgyMzY1ODcsImV4cCI6MTcyODMyMjk4N30.wJwgSr2e4yVIxUcpnl_Z5gmmrhCsgYqwD40L_nOQVsg

### Login
POST http://localhost:4000/auth/login
Content-Type: application/json

{
    "email": "wimx@tut.by",
    "password": "12345lL@"
}

### Logout 
POST  http://localhost:4000/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmNzdiNjdmZS0wYjc2LTQyOTEtOTVmYS0yM2QwOWMzNTc1YjEiLCJpYXQiOjE3MjgyMzcyMjUsImV4cCI6MTcyODIzNzI4NX0.cFzw7VD8m0AdEZaGqXLF2pPWlRayIQodYRB0l7tX_hg


### Refresh Token 
POST   http://localhost:4000/auth/refresh-token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmNzdiNjdmZS0wYjc2LTQyOTEtOTVmYS0yM2QwOWMzNTc1YjEiLCJpYXQiOjE3MjgyMzcyNjUsImV4cCI6MTcyODg0MjA2NX0.3v-rzt0F_Aq0D8dU7quU6NcBJQ-tkDmIFo2vzfgMmDo

### Обновление пароля пользователя
PATCH http://localhost:4000/user/f77b67fe-0b76-4291-95fa-23d09c3575b1/update-user-data
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmNzdiNjdmZS0wYjc2LTQyOTEtOTVmYS0yM2QwOWMzNTc1YjEiLCJpYXQiOjE3NDUzNDEwNDcsImV4cCI6MTc0NTM0MTEwN30.ZBKFHEVEUlV55MW4sxrLCRWqG3yYwZWDUu6ZOPZdZ0s

{
    "password": "NewSecure@P4ssw0rd",
    "confirmPassword": "NewSecure@P4ssw0rd"
}

### Обновление имени пользователя
PATCH http://localhost:4000/user/f77b67fe-0b76-4291-95fa-23d09c3575b1/update-user-data
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmNzdiNjdmZS0wYjc2LTQyOTEtOTVmYS0yM2QwOWMzNTc1YjEiLCJpYXQiOjE3NDUzNDEwNDcsImV4cCI6MTc0NTM0MTEwN30.ZBKFHEVEUlV55MW4sxrLCRWqG3yYwZWDUu6ZOPZdZ0s

{
    "name": "Игорь"
}

### Удаление аккаунта пользователя
DELETE http://localhost:4000/user/f77b67fe-0b76-4291-95fa-23d09c3575b1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmNzdiNjdmZS0wYjc2LTQyOTEtOTVmYS0yM2QwOWMzNTc1YjEiLCJpYXQiOjE3MjgyMzcyNjUsImV4cCI6MTcyODg0MjA2NX0.3v-rzt0F_Aq0D8dU7quU6NcBJQ-tkDmIFo2vzfgMmDo

### Получение всех игр
GET http://localhost:4000/games/search
Content-Type: application/json

{
    "search": "mortal kombat 12"
}

### Получение всех отзывов пользователя
GET http://localhost:4000/reviews
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjOTc2M2M4Yy1kMjM2LTQwMjktYjQ4Yy0yNjQ4ZDFhNDVjZGMiLCJpYXQiOjE3NDYwMjAzNTYsImV4cCI6MTc0NjAyMDQxNn0.m6opFM6cC_LL6zjYw4rSm9WINMbs-KYVUZd_tlb-Dzc

### Создание нового отзыва (без изображения)
POST http://localhost:4000/reviews
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjOTc2M2M4Yy1kMjM2LTQwMjktYjQ4Yy0yNjQ4ZDFhNDVjZGMiLCJpYXQiOjE3NDYwMjAyODksImV4cCI6MTc0NjAyMDM0OX0.FdwEDIumEjG3mYHt--tGdogv3nAHqAgfIxhhrJ-uITM

{
    "title": "Отличная игра!",
    "status": "В процессе",
    "playTime": "32ч",
    "rating": "4.5",
    "score": "4.5",
    "plotScore": "4.0",
    "artScore": "5.0",
    "gameplayScore": "4.5",
    "difficulty": "Легкая",
    "trophies": "5",
    "review": "Отличная игра с захватывающим сюжетом и великолепной графикой. Боевая система глубокая и интересная, хотя некоторые боссы излишне сложные. Обязательна к прохождению всем любителям жанра."
}

### Создание нового отзыва с изображением
POST http://localhost:4000/reviews
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjOTc2M2M4Yy1kMjM2LTQwMjktYjQ4Yy0yNjQ4ZDFhNDVjZGMiLCJpYXQiOjE3NDYwMjAyODksImV4cCI6MTc0NjAyMDM0OX0.FdwEDIumEjG3mYHt--tGdogv3nAHqAgfIxhhrJ-uITM

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="title"

Отличная игра!
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="status"

В процессе
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="playTime"

32ч
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="rating"

4.5
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="score"

4.5
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="plotScore"

4.0
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="artScore"

5.0
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="gameplayScore"

4.5
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="difficulty"

Легкая
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="trophies"

5
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="review"

Отличная игра с захватывающим сюжетом и великолепной графикой.
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="img"; filename="screenshot.jpg"
Content-Type: image/jpeg

< ./screenshot.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Создание отзыва с внешней ссылкой на изображение
POST http://localhost:4000/reviews
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjOTc2M2M4Yy1kMjM2LTQwMjktYjQ4Yy0yNjQ4ZDFhNDVjZGMiLCJpYXQiOjE3NDYwMjAyODksImV4cCI6MTc0NjAyMDM0OX0.FdwEDIumEjG3mYHt--tGdogv3nAHqAgfIxhhrJ-uITM

{
    "title": "Отличная игра!",
    "status": "В процессе",
    "playTime": "32ч",
    "rating": "4.5",
    "score": "4.5",
    "plotScore": "4.0",
    "artScore": "5.0",
    "gameplayScore": "4.5",
    "difficulty": "Легкая",
    "trophies": "5",
    "review": "Отличная игра с захватывающим сюжетом и великолепной графикой.",
    "imgUrl": "https://example.com/screenshot.jpg"
}

### Добавление отзыва в избранное
POST http://localhost:4000/reviews/favorite/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjOTc2M2M4Yy1kMjM2LTQwMjktYjQ4Yy0yNjQ4ZDFhNDVjZGMiLCJpYXQiOjE3NDYwMjAyODksImV4cCI6MTc0NjAyMDM0OX0.FdwEDIumEjG3mYHt--tGdogv3nAHqAgfIxhhrJ-uITM
